apiVersion: batch/v1
kind: Job
metadata:
  name: spid-installer-job
spec:
  template:
    spec:
      containers:
        - name: installer-single
          image: jangalian/spid-provider-installer:0.1
#          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 1