apiVersion: batch/v1
kind: Job
metadata:
  name: spid-installer-job
spec:
  template:
    spec:
      serviceAccountName: spid-installer-sa
      containers:
        - name: installer-single
          image: jangalian/spid-provider-installer:3.5
      restartPolicy: Never
  backoffLimit: 4