apiVersion: v1
kind: ServiceAccount
metadata:
  name: spid-installer-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: entando
  name: spid-install-role
rules:
  - apiGroups: ["", "role.rbac.authorization.k8s.io", "rbac.authorization.k8s.io", "authorization.k8s.io", "networking.k8s.io"] # "" indicates the core API group
    resources: ["pods/exec", "pods", "namespaces", "secrets", "ingresses"]
    verbs: ["create", "list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spid-install-role-binding-sa
  namespace: entando
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: spid-install-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: spid-installer-sa
    namespace: entando